name-template: $RESOLVED_VERSION
tag-template: $RESOLVED_VERSION
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
template: |
  ## Changes

  $CHANGES
