name = "kippu"
main = "src/index.ts"
compatibility_date = "2024-02-08"

[[kv_namespaces]]
binding = "KIPS_KEYS"
id = "177f177f4b9db26143b69ae1799be2c25c55"

[[kv_namespaces]]
binding = "KIPS_LOGINS"
id = "ea27932fa70645e4ba562fbd4ddd9053"

[[kv_namespaces]]
binding = "KIPS_KEY_BY_MAIL"
id = "bb521cc376f547dcba3ae2542360b7e3"

[[kv_namespaces]]
binding = "KIPS_PASS_CLASS"
id = "5a6c29e943fa40aa9ce550cdbe7f1a5a"
